application: powerful-fortress-5090
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: pycrypto
  version: "2.6"
  
handlers:
- url: /.*
  script: app.WSGIApplication
  
  